### PR TITLE
Issue #231: Fix 'version' command bug

### LINKED ISSUE #231: 'version' bootstrap issue
The `version` command doesn't work properly:

```bash
Command backdrop-drush-version needs a higher bootstrap level to run - you will need to invoke drush from a more functional Drupal environment to run this command.   [error]
The drush command 'version' could not be executed.                                                                                                                    [error]
```

This also cases an issue in Lando: https://github.com/lando/lando/issues/2695

### PR DESCRIPTION
**Pull request by ghost**
Fixes https://github.com/backdrop-contrib/backdrop-drush-extension/issues/231

### CODE REVIEW

**Comment by serundeputy** [comment]
thanks @BWPanda 

this did not work for me:

```bash
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   632  100   632    0     0   3001      0 --:--:-- --:--:-- --:--:--  3009
100 4879k  100 4879k    0     0  4771k      0  0:00:01  0:00:01 --:--:-- 6757k
Command backdrop-drush-version needs a higher bootstrap level to run - you will need to invoke drush from a more functional Drupal environment to run this command.                                                                                  [error]
The drush command 'version' could not be executed.                                                                                                                                                                                                   [error]
ERROR ==> The drush command 'version' could not be executed.                                                                                                                                                                                                   [error] 

```

**Comment by ghost** [comment]
@serundeputy I wasn't sure how to test this with Lando... But it does fix the more general problem described in the linked issue.

**Comment by klonos** [comment]
Hey @BWPanda and @serundeputy 👋 ...I guess https://github.com/backdrop-contrib/backdrop-drush-extension/pull/233 is an attempt to fix the test failures. Right? ...otherwise, it seems to be @BWPanda's PR + a commit to revert composer to 1.x in `.travis.yml`.

**Comment by ghost** [comment]
@klonos Seems that way...

**Comment by ghost** [comment]
I changed the bootstrap for the 'version' command from `DRUSH_BOOTSTRAP_DRUSH` (which is only used in one other place - `grn.drush.inc`) to `DRUSH_BOOTSTRAP_NONE` (which is used in 5 other places. Hopefully this makes it easier to understand what this line means.

**Pull request merged**
